# Generated by Django 3.1.6 on 2021-03-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
