# Generated by Django 3.1.6 on 2021-03-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='number',
            new_name='number_str',
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
