# Generated by Django 3.1.6 on 2021-03-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_str',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites_str',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='w_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='This is an example title', max_length=100),
        ),
    ]
