# Generated by Django 3.1.6 on 2021-03-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0002_auto_20210305_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number_str',
        ),
    ]
