# Generated by Django 3.1.6 on 2021-03-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0002_remove_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
