# Generated by Django 3.1.6 on 2021-03-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0004_auto_20210305_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='TEST', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfu_academic_api_parser.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_str',
            field=models.CharField(default='TEST 123', max_length=12),
        ),
    ]
