# Generated by Django 3.1.6 on 2021-03-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0005_auto_20210305_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='This is an example title', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
