# Generated by Django 3.1.6 on 2021-03-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0006_auto_20210307_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(),
        ),
    ]
