# Generated by Django 3.1.6 on 2021-03-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0007_auto_20210307_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(default='This is an example of a prerequisite', max_length=1000),
        ),
    ]
