# Generated by Django 3.1.6 on 2021-03-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfu_academic_api_parser', '0009_auto_20210308_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereqArray',
            field=models.CharField(default=['Ford', 'Volvo', 'BMW'], max_length=1000),
        ),
    ]
