# Generated by Django 3.1.6 on 2021-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='This is an example title', max_length=50)),
                ('prerequisite', models.CharField(default='This is an example of a prerequisite', max_length=1000)),
                ('prereqList', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
