# Generated by Django 3.1.6 on 2021-03-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetree',
            name='prereqList',
            field=models.CharField(default=['Ford', 'Volvo', 'BMW'], max_length=1000),
        ),
    ]
