# Generated by Django 3.1.6 on 2021-03-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemode', '0002_auto_20210312_2210'),
        ('treemode', '0002_auto_20210312_2227'),
    ]

    operations = [
    ]
