# Generated by Django 3.1.6 on 2021-03-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemode', '0003_merge_20210316_2039'),
        ('treemode', '0003_merge_20210313_0636'),
    ]

    operations = [
    ]
